account.balance.other=<gray><prefix> <green><player>'s</green> Kontostand beträgt <green><balance><symbol></green></gray>
account.balance.self=<gray><prefix> Dein Kontostand beträgt <green><balance><symbol></green></gray>
account.balance.world.other=<gray><prefix> <green><player>'s</green> Kontostand in <green><world></green> beträgt <green><balance><symbol></green></gray>
account.balance.world.self=<gray><prefix> Dein Kontostand in <green><world></green> beträgt <green><balance><symbol></green></gray>
account.created.other=<gray><prefix> Ein neues Konto wurde für <green><player></green> erstellt</gray>
account.created.self=<gray><prefix> Ein neues Konto wurde für wurde für dich erstellt</gray>
account.created.world.other=<gray><prefix> Ein neues Konto wurde für <green><player></green> in <green><world></green> erstellt</gray>
account.created.world.self=<gray><prefix> Ein neues Konto wurde für dich in <green><world></green> erstellt</gray>
account.deleted.other=<gray><prefix> <green><player>'s</green> Konto wurde gelöscht</gray>
account.deleted.self=<gray><prefix> Dein Konto wurde gelöscht</gray>
account.deleted.world.other=<gray><prefix> <green><player>'s</green> Konto in <green><world></green> wurde gelöscht</gray>
account.deleted.world.self=<gray><prefix> Dein Konto in <green><world></green> wurde gelöscht</gray>
account.exists.other=<red><prefix> <dark_red><player></dark_red> hat bereits ein Konto</red>
account.exists.self=<red><prefix> Du hast bereits ein Konto</red>
account.exists.world.other=<red><prefix> <dark_red><player></dark_red> hat bereits ein Konto in <dark_red><world></dark_red></red>
account.exists.world.self=<red><prefix> Du hast bereits ein Konto in <dark_red><world></dark_red></red>
account.balance-range.invalid=<red><prefix> Der resultierende Kontostand würde den erlaubten Bereich dieser Währung überschreiten</red>
account.funds=<red><prefix> Du hast nicht genug Geld für diese Transaktion</red>
account.not-found.other=<red><prefix> <dark_red><player></dark_red> hat kein Konto</red>
account.not-found.self=<red><prefix> Du hast kein Konto</red>
account.not-found.world.other=<red><prefix> <dark_red><player></dark_red> hat kein Konto in <dark_red><world></dark_red></red>
account.not-found.world.self=<red><prefix> Du hast kein Konto in <dark_red><world></dark_red></red>
account.prune.none.world=<red><prefix> Es wurden keine Konten in <dark_red><world></dark_red> bereinigt</red>
account.prune.none=<red><prefix> Es wurden keine Konten bereinigt</red>
account.prune.success.world=<gray><prefix> <green><pruned></green> Konten wurden in <green><world></green> bereinigt</gray>
account.prune.success=<gray><prefix> <green><pruned></green> Konten wurden bereinigt</gray>
argument.currency.unknown=<red><prefix> Unbekannte Währung</red>
balance.deposited.world=<gray><prefix> <green><player>'s</green> Kontostand in <green><world></green> wurden <green><amount><symbol></green> hinzugefügt <dark_gray>(<green><balance><symbol></green>)</dark_gray></gray>
balance.deposited=<gray><prefix> <green><player>'s</green> Kontostand wurden <green><amount><symbol></green> hinzugefügt <dark_gray>(<green><balance><symbol></green>)</dark_gray></gray>
balance.reset.world=<gray><prefix> <green><player>'s</green> Kontostand in <green><world></green> wurde auf <green><balance><symbol></green> zurückgesetzt</gray>
balance.reset=<gray><prefix> <green><player>'s</green> Kontostand wurde auf <green><balance><symbol></green> zurückgesetzt</gray>
balance.set.world=<gray><prefix> <green><player>'s</green> Kontostand in <green><world></green> wurde auf <green><balance><symbol></green> gesetzt</gray>
balance.set=<gray><prefix> <green><player>'s</green> Kontostand wurde auf <green><balance><symbol></green> gesetzt</gray>
balance.top-list.empty=<red><prefix> Auf dieser Seite gibt es keine Konten</red>
balance.top-list.header.world=<gray><prefix> Die reichsten Spieler in <green><world></green></gray>
balance.top-list.header=<gray><prefix> Die reichsten Spieler auf dem Server</gray>
balance.top-list.total.world=<gray><prefix> Gesamtreichtum in <green><world></green> beträgt <green><symbol><total></green></gray>
balance.top-list.total=<gray><prefix> Gesamtreichtum des Servers beträgt <green><symbol><total></green></gray>
balance.top-list=<gray>#<rank> <green><player></green> – <yellow><balance><symbol></yellow> <dark_gray>(<white><worth></white>)</dark_gray></gray>
balance.withdrawn.world=<gray><prefix> <green><player>'s</green> Kontostand in <green><world></green> wurden <green><amount><symbol></green> entfernt <dark_gray>(<green><balance><symbol></green>)</dark_gray></gray>
balance.withdrawn=<gray><prefix> <green><player>'s</green> Kontostand wurden <green><amount><symbol></green> entfernt <dark_gray>(<green><balance><symbol></green>)</dark_gray></gray>
bank.access.denied=<red><prefix> Du darfst diese Bankaktion nicht ausführen</red>
bank.balance.other=<gray><prefix> Bank <green><bank></green> von <green><owner></green> enthält <green><symbol><balance></green></gray>
bank.balance.self=<gray><prefix> Deine Bank <green><bank></green> enthält <green><symbol><balance></green></gray>
bank.created.other=<gray><prefix> Bank <green><bank></green> für <green><owner></green> erstellt</gray>
bank.created.self=<gray><prefix> Deine Bank <green><bank></green> wurde erstellt</gray>
bank.deleted.other=<gray><prefix> Bank <green><bank></green> von <green><owner></green> gelöscht</gray>
bank.deleted.self=<gray><prefix> Deine Bank <green><bank></green> wurde gelöscht</gray>
bank.deposit=<gray><prefix> <green><symbol><amount></green> in <green><bank></green> eingezahlt <dark_gray>(<green><symbol><balance></green>)</dark_gray></gray>
bank.exists.other=<red><prefix> Bank <dark_red><bank></dark_red> konnte nicht für <dark_red><owner></dark_red> erstellt werden</red>
bank.exists.self=<red><prefix> Du besitzt bereits eine Bank oder <dark_red><bank></dark_red> ist schon vergeben</red>
bank.info.balance=<gray><prefix> Kontostand: <green><symbol><balance></green></gray>
bank.info.header=<gray><prefix> Bank <green><bank></green></gray>
bank.info.members=<gray><prefix> Mitglieder: <green><members></green></gray>
bank.info.owner=<gray><prefix> Eigentümer: <green><owner></green></gray>
bank.list.empty=<red><prefix> Auf dieser Seite gibt es keine Banken</red>
bank.list.entry=<gray><prefix> <green><bank></green> <dark_gray>(Eigentümer: <white><owner></white>)</dark_gray></gray>
bank.list.header=<gray><prefix> Banken auf Seite <green><page></green></gray>
bank.members.add=<gray><prefix> <green><member></green> zu <green><bank></green> hinzugefügt</gray>
bank.members.empty=<red><prefix> Diese Bank hat keine Mitglieder</red>
bank.members.entry=<gray><prefix> - <green><member></green></gray>
bank.members.header=<gray><prefix> Mitglieder von <green><bank></green></gray>
bank.members.owner=<gray><prefix> Eigentum von <green><bank></green> an <green><member></green> übertragen</gray>
bank.members.remove=<gray><prefix> <green><member></green> aus <green><bank></green> entfernt</gray>
bank.not-found.name=<red><prefix> Bank <dark_red><bank></dark_red> existiert nicht</red>
bank.not-found.other=<red><prefix> <dark_red><owner></dark_red> besitzt keine Bank</red>
bank.not-found.self=<red><prefix> Du besitzt keine Bank</red>
bank.top.empty=<red><prefix> Auf dieser Seite gibt es keine Banken</red>
bank.top.entry=<gray>#<rank> <green><bank></green> – <yellow><symbol><balance></yellow></gray>
bank.top.header=<gray><prefix> Reichste Banken auf Seite <green><page></green></gray>
bank.transfer=<gray><prefix> <green><symbol><amount></green> von <green><bank></green> nach <green><target></green> transferiert</gray>
bank.withdraw=<gray><prefix> <green><symbol><amount></green> aus <green><bank></green> abgehoben <dark_gray>(<green><symbol><balance></green>)</dark_gray></gray>
currency.balance-range.invalid=<red><prefix> Das Mindestguthaben darf das Maximalguthaben nicht überschreiten</red>
currency.created=<gray><prefix> Währung <green><currency></green> mit Symbol <green><symbol></green> und <green><digits></green> Nachkommastellen erstellt</gray>
currency.default.current=<gray><prefix> Die Standardwährung ist <green><currency></green> <dark_gray>(</dark_gray><green><symbol></green><dark_gray>)</dark_gray></gray>
currency.default.updated=<gray><prefix> Standardwährung auf <green><currency></green> gesetzt <dark_gray>(</dark_gray><green><symbol></green><dark_gray>)</dark_gray></gray>
currency.delete.default=<red><prefix> Die Standardwährung <dark_red><currency></dark_red> kann nicht gelöscht werden</red>
currency.deleted=<gray><prefix> Währung <green><currency></green> gelöscht</gray>
currency.exists=<red><prefix> Währung <dark_red><currency></dark_red> existiert bereits</red>
currency.info.fractional-digits=<gray><prefix> Nachkommastellen: <green><digits></green></gray>
currency.info.header=<gray><prefix> Währung <green><currency></green></gray>
currency.info.locales=<gray><prefix> Sprachen: <green><locales></green></gray>
currency.info.max-balance=<gray><prefix> Maximalguthaben: <green><balance></green></gray>
currency.info.min-balance=<gray><prefix> Mindestguthaben: <green><balance></green></gray>
currency.info.plural=<gray><prefix> Plural: <green><name></green></gray>
currency.info.singular=<gray><prefix> Singular: <green><name></green></gray>
currency.info.starter-balance=<gray><prefix> Startguthaben: <green><balance></green></gray>
currency.info.symbol=<gray><prefix> Symbol: <green><symbol></green></gray>
currency.list.empty=<red><prefix> Es gibt keine Währungen</red>
currency.list.entry.default=<gray><prefix> <white><currency></white><dark_gray> (</dark_gray><gold><symbol></gold><dark_gray>) - </dark_gray><white><amount></white><dark_gray> (</dark_gray><gray><digits> Nachkommastellen</gray><white><bounds></white><dark_gray>, </dark_gray><gold>Standard</gold><dark_gray>)</dark_gray></gray>
currency.list.entry=<gray><prefix> <white><currency></white><dark_gray> (</dark_gray><gold><symbol></gold><dark_gray>) - </dark_gray><white><amount></white><dark_gray> (</dark_gray><gray><digits> Nachkommastellen</gray><white><bounds></white><dark_gray>)</dark_gray></gray>
currency.list.header=<gray><prefix> Währungen <dark_gray>(</dark_gray><white><count></white><dark_gray>):</dark_gray></gray>
currency.updated.display-name.plural.cleared=<gray><prefix> Pluralen Anzeigenamen von <green><currency></green> für <green><locale></green> entfernt</gray>
currency.updated.display-name.plural=<gray><prefix> Pluralen Anzeigenamen von <green><currency></green> für <green><locale></green> aktualisiert</gray>
currency.updated.display-name.singular.cleared=<gray><prefix> Singularen Anzeigenamen von <green><currency></green> für <green><locale></green> entfernt</gray>
currency.updated.display-name.singular=<gray><prefix> Singularen Anzeigenamen von <green><currency></green> für <green><locale></green> aktualisiert</gray>
currency.updated.fractional-digits=<gray><prefix> Nachkommastellen von <green><currency></green> auf <green><digits></green> gesetzt</gray>
currency.updated.max-balance.cleared=<gray><prefix> Maximalguthaben von <green><currency></green> entfernt</gray>
currency.updated.max-balance=<gray><prefix> Maximalguthaben von <green><currency></green> auf <green><balance></green> gesetzt</gray>
currency.updated.min-balance.cleared=<gray><prefix> Mindestguthaben von <green><currency></green> entfernt</gray>
currency.updated.min-balance=<gray><prefix> Mindestguthaben von <green><currency></green> auf <green><balance></green> gesetzt</gray>
currency.updated.starter-balance=<gray><prefix> Startguthaben von <green><currency></green> auf <green><balance></green> gesetzt</gray>
currency.updated.symbol=<gray><prefix> Symbol von <green><currency></green> auf <green><symbol></green> gesetzt</gray>
currency.starter-balance.invalid=<red><prefix> Das Startguthaben muss innerhalb des erlaubten Guthabenbereichs liegen</red>
currency.value.unlimited=unbegrenzt
nothing.changed=<red><prefix> Es konnte nichts geändert werden</red>
operation.failed=<red><prefix> Die Aktion ist unerwartet fehlgeschlagen</red>
player.define=<red><prefix> Du musst mindestens einen Spieler angeben</red>
player.pay.incoming=<gray><prefix> <green><player></green> hat dir <green><amount><symbol></green> überwiesen</gray>
player.pay.outgoing=<gray><prefix> Du hast <green><amount><symbol></green> an <green><player></green> überwiesen</gray>
player.pay.self=<red><prefix> Du kannst dir selber kein Geld überweisen</red>
